Mejoras combate + fix bugs + items
UrukBartas/Game pull request #14
Opened 2024-02-08 19:28 UTC by chmolto

- Fix carga quest en router
- Mejorar animaciones combate
- Fix blocks y crits bugueados
- Generar shied + ring + totem

2024-02-11 16:48 UTC, tihomir22 requested changes

2024-02-11 16:48 UTC, tihomir22 commented on src/modules/game/activities/quests/quest-fight/quest-fight.component.ts
> +  encapsulation: ViewEncapsulation.None,
Aplica los estilos globales en el styles.scss si este es el unico fichero con el VE.None sino dejalo como está.

2024-02-11 16:48 UTC, tihomir22 commented on src/modules/game/activities/quests/quest-result/quest-result.component.ts
> +    this.questService
Añadiria un takeUntilDestroyed para evitar que se quede atorao.

https://angular.io/api/core/rxjs-interop/takeUntilDestroyed

2024-02-12 20:28 UTC, chmolto commented on src/modules/game/activities/quests/quest-result/quest-result.component.ts
> +    this.questService
Ya tiene el take(1), cuando recibe la respuesta se destruye auto

2024-02-13 08:28 UTC, merged