Style, surrender, modals, show all player stats inventory & general improvements
UrukBartas/Game pull request #17
Opened 2024-02-17 15:58 UTC by chmolto

2024-02-18 19:21 UTC, tihomir22 requested changes

2024-02-18 19:21 UTC, tihomir22 commented on src/modules/game/activities/quests/quest-fight/quest-fight.component.html
> +<ng-template #playerStats>
esto se pued ereutilizar y que se cree o bien un componente a parte para que muestre los stats o un template y que se reutilice con el ngTemplateOutlet, checkea algunos ejemplos, semi-duplicar el codigo no mola

2024-02-19 08:15 UTC, chmolto commented on src/modules/game/activities/quests/quest-fight/quest-fight.component.html
> +<ng-template #playerStats>
Ya man es una shit, pero el problema es que el [ngbTooltip] solo acepta templates, y no se le pueden pasar variables si quiera.

Lo que puedo hacer es hacer una template intermedia para poder pasarle una variable a otra template, ahora lo checkeo

2024-02-19 08:34 UTC, chmolto commented on src/modules/game/activities/quests/quest-fight/quest-fight.component.html
> +<ng-template #playerStats>
Bueno nvm, lo subo en la siguiente PR de shop

2024-02-19 09:56 UTC, tihomir22 commented on src/modules/game/activities/quests/quest-fight/quest-fight.component.html
> +<ng-template #playerStats>
suave

2024-02-19 09:56 UTC, merged