Shop + consumibles
UrukBartas/Game pull request #19
Opened 2024-02-29 22:04 UTC by chmolto

https://github.com/UrukBartas/Game/assets/22659045/26ec9fd2-f9cc-464a-8cdd-91dec875d3c7

(falta por implementar consumibles)

2024-03-04 19:52 UTC, chmolto commented
Cuando quieras jala el ganso men @tihomir22

2024-03-09 18:38 UTC, tihomir22 commented on src/modules/game/activities/quests/quest-fight/components/consumable-modal.component.scss
> +  background-color: #1f1f1e;
No tenemos alguna variable para el background  y el bg color?

2024-03-09 18:43 UTC, tihomir22 commented on src/modules/game/activities/shop/components/daily-roll-button.component.ts
> +  setDailyRollButtonStatus() {
Me imagino que la idea de esto es que una vez haga el reroll tenga que esperar otras 24h hasta el siguiente y lo lanzas fuera del zone de angular para que continue descontando incluso en diferente vista/activity/ruta

Vale, pero si refrescamos eso no se reinicia porque reside en memoria o me estoy perdiendo algo :D ?

2024-03-09 18:44 UTC, tihomir22 commented on src/modules/game/activities/shop/shop.component.scss
> +    background: #00000073;
Aqui veo colores que se podrian reemplazar por variables asi no tenemos problemas de recolarización en el futuro si nos hiciera falta

2024-03-09 18:46 UTC, tihomir22 commented on src/modules/game/activities/shop/shop.component.ts
> +      this.triggerDialog('OHMYGOD A MYTHICAL WOOOOOW!!! 💥😱🎆', 2000);
Aquí te secuestra el orcaso y te roba el mythic

2024-03-09 18:47 UTC, tihomir22 requested changes
No hay error, hay warning

2024-03-13 12:01 UTC, chmolto commented on src/modules/game/activities/shop/components/daily-roll-button.component.ts
> +  setDailyRollButtonStatus() {
Tanto a esto como al ViewportService les he metido el ngZone para que se ejecuten fuera de la detección de cambios de angular

Si te fijas antes cuando hacías un resize, los tamaños de los item-box y demás cosas que dependían del ViewportService no se actualizaban hasta que interactuaras con la web haciendo clicks, etc, con esto lo evitas.
Y para este botón lo mismo, si lo ejecutas dentro del marco de detección de eventos de angular va a pedales, con esto va mas fino xD

Y el timer se refresca desde el back cada vez que se entra a la shop por lo que no necesitamos guardarlo

2024-03-13 20:00 UTC, merged